import "@repo/ui/globals.css";
import { Button } from "@repo/ui/components/ui/button";

import type { Metadata } from "next";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <nav className="absolute top-0 left-0 right-0 z-50">
          <div className="container mx-auto flex items-center justify-between py-6">
            <div className="flex gap-8">
              <a
                href="#"
                className="text-sm text-white hover:text-white/80 transition-colors"
              >
                Home
              </a>
              <a
                href="#"
                className="text-sm text-white hover:text-white/80 transition-colors"
              >
                Gallery
              </a>
              <a
                href="#"
                className="text-sm text-white hover:text-white/80 transition-colors"
              >
                Hotels
              </a>
            </div>
            <Button
              variant="outline"
              size="sm"
              className="rounded-full px-6 text-white border-white bg-teal-900/30 py-2 hover:bg-white/20"
            >
              Log in
            </Button>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}

